[tool.poetry]
name = "opteemo-hello-poetry"
version = "0.1.0"
description = ""
authors = ["Yannick Mulot <ymulot@opteemo.fr>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"